image: golang:latest

pipelines:
  branches:
    jared:
      - parallel:
        - step:
            name: Build ocgo
            image: golang:latest
            script:
              - ./scripts/ocgo/build.sh
            artifacts:
              - ./scripts/ocgo/ocgo
