---
- name: provision hosts.yaml
  hosts: proxmox
  tasks:
    - name: install packages
      apt:
        state: latest
        update_cache: true
        name:
          - zsh
          - curl
          - fontconfig
          - fzf
          - gcc
          - git
          - htop
          - iperf
          - jq
          - ncdu
          - nmap
          - proxychains-ng
          - sshuttle
          - tmux
          - screen
          - watch
          - wget
          - bat
          - ripgrep

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: install fonts
      shell: |
        if [ ! -f "$HOME/.local/share/fonts/MesloLGS NF Regular.ttf" ]; 
        then
          mkdir -p ~/.local/share/fonts && cd ~/.local/share/fonts
          wget "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
          wget "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
          wget "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
          wget "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
          fc-cache -f -v
        fi

    - name: Install ZSH plugins
      shell: |
        cd $HOME
        [ -d "$HOME/.oh-my-zsh" ] || sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
        [ -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ] || git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
        [ -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ] || git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-$HOME//.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        [ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ] || git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME//.oh-my-zsh/custom}/themes/powerlevel10k

    - name: Create symbolic links
      copy:
        src: '../dotfiles/{{ item }}'
        dest: '~/{{ item }}'
      with_items:
        - '.bash_profile'
        - '.bashrc'
        - '.vimrc'
        - '.zshrc'
        - '.p10k.zsh'
        - '.tmux.conf.local'
        - '.tmux.conf'

    - name: change shell to zsh
      shell: 'chsh -s /bin/zsh'