## PATH ##
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="$PATH:/opt/nvim-linux64/bin"

## BLE.SH ##
# https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A71-Introduction
# install ble.sh if needed
if [ ! -f "$HOME/.local/share/blesh/ble.sh" ]; then
    cd /tmp || exit
    git clone --recursive --depth 1 --shallow-submodules https://github.com/akinomyoga/ble.sh.git
    make -C ble.sh install PREFIX="$HOME/.local"
    cd "$HOME" || exit
fi
# source ble.sh and config
[[ $- == *i* ]] &&
    source "$HOME/.local/share/blesh/ble.sh" --rcfile "$HOME/.blerc"

set -o vi # use vi mode for bash keys
# set -o emacs # use emacs mode (default) for bash keys

# use the latest version of nvim on debian
if [[ -f /etc/debian_version ]]; then
    export PATH="$PATH:/opt/nvim-linux64/bin"
fi

## EXPORT ##
export EDITOR=nvim
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY="YES"
# conditional open api key - only works on macos with pw set va keychain

if command -v security &>/dev/null; then
    OPENAI_API_KEY=$(security find-generic-password -s openai -a autocomplete -w)
else
    OPENAI_API_KEY=""
fi
export OPENAI_API_KEY

## Prompt ##
# Define color codes
ORANGE="\[\e[38;5;214m\]"
RESET="\[\e[0m\]"

# Define the base part of the prompt
PROMPT_COMMAND='PS1_CMD1=\($(git branch --show-current 2>/dev/null)\)'
PS1='\[\e[38;5;34;3m\]${PS1_CMD1}\[\e[0m\]'
# PS1_BASE='\[\e[38;5;30m\]\W\[\e[0m\] \[\e[38;5;34;2;3m\]${PS1_CMD1}\[\e[0m\]\[\e[38;5;64;1m\] ❯ \[\e[0m\]'
PS1_BASE='\[\e[38;5;249;1m\]\W\[\e[0m\] \[\e[90;2;3m\]${PS1_CMD1}\[\e[0m\]\[\e[38;5;64;1m\] ❯ \[\e[0m\]'
# Check if an SSH session is active and include the short hostname if it is
if [[ -n "$SSH_CONNECTION" ]]; then
    PS1="${ORANGE}\h${RESET}:$PS1_BASE"
else
    PS1=$PS1_BASE
fi

## Functions ##
get_column() {
    if [ "$#" -lt 2 ]; then
        echo "Usage: get_column <file> <column_number>"
        exit 1
    fi

    file=$1
    column=$2

    if [ ! -f "$file" ]; then
        echo "File not found: $file"
        exit 1
    fi

    awk -v col="$column" -F ' ' '{print $col}' "$file"
}

## GO config ##
export GOPATH="$HOME/go"
export GOCACHE="$HOME/.cache/go"
export GOMAXPROCS=$(nproc)
export PATH="$PATH:$GOPATH/bin"

## ALIAS ##
# common
alias ls='ls --color=auto'
alias ll='ls -lah'
alias gs="git status"
alias ks='kubectl -n kube-system'
alias grep='rg'
alias cat='batcat -pp'
alias diff='colordiff -y --suppress-common-lines'
alias lg='lazygit'
alias x='exit'
alias ta='tmux a -t'
alias v='nvim'
alias jq='jq -C'
alias less='less -R'
alias gb='go build -v'
alias rb='exec bash' # reload bash
alias gpl='git pull'
alias gph='git push'

# macos
if [ "$(uname)" == "Darwin" ]; then
    export SHELL="/opt/homebrew/bin/bash"
    alias update='$HOME/.config/scripts/update_macos.sh'
    alias start_meeting="/Users/jared/Documents/scripts/redlight.sh"
    alias stop_meeting="/Users/jared/Documents/scripts/bluelight.sh"
    alias tacc="ssh -i $HOME/.ssh/tacc_id_ras jsc3642@stampede2.tacc.utexas.edu"
    alias reset_network="sudo route -n flush && sudo dscacheutil -flushcache"
    alias tastyfish="ssh jared@tastyfish.local"
    alias crawfish="ssh -i $HOME/.ssh/jcampbell7899@utexas.edu.pem -p6137 jared@crawfish.infosec.utexas.edu"
    alias prox_ssh="ssh -o StrictHostKeyChecking=false -J void-jumpbox-01 "
    alias notes="vim $HOME/Documents/Notes/documentation/notes.md"
    alias ansible_site="/opt/ansible/site.yaml"
    alias ip_lookup="/opt/chomp/.venv/bin/python3 /opt/chomp/tsc_tools/tsc_tools.py -o --ip_lookup "
    alias ip_bq="/opt/chomp/.venv/bin/python3 /opt/chomp/tsc_tools/tsc_tools.py -o --ip_quarantine"
    alias nomad_ots="ssh -t nomad-client-001 'podman run -it --rm --network=ots_network --dns=1.1.1.1 --cap-add=NET_RAW -v /opt/chomp:/opt/chomp:ro -v /opt/chompout:/opt/chompout:rw iso-registry.infosec.utexas.edu/utexasiso-default /bin/bash'"
    alias nmap_ots="ssh -t nomad-client-001 'podman run -it --rm --network=ots_network --dns=1.1.1.1 --cap-add=NET_RAW -v /opt/chomp:/opt/chomp:ro -v /opt/chompout:/opt/chompout:rw iso-registry.infosec.utexas.edu/utexasiso-scavenger /bin/bash'"
    alias nomad_git='ansible nomad_clients,nomad_baremetal -b -m shell -a "git -C /opt/nomad pull; git -C /opt/chomp pull; git -C /opt/chomptest pull"'
    alias refresh_dns='$HOME/.config/scripts/refresh_dns.sh'
    alias pansible='$HOME/.config/scripts/pansible.sh'
    alias ans='source .venv/bin/activate.fish && source setup/.env.jared'
    alias du='dust'
    alias df='duf'
    alias ls='lsd -A'
    alias cat='bat -pp'
fi

# load direnv
eval "$(direnv hook bash)"

# needs to be at end of file
[[ ${BLE_VERSION-} ]] && ble-attach
