#!/bin/bash

get_column() {
    if [ "$#" -lt 2 ]; then
        echo "Usage: get_column <file> <column_number>"
        exit 1
    fi

    file=$1
    column=$2

    if [ ! -f "$file" ]; then
        echo "File not found: $file"
        exit 1
    fi

    awk -v col="$column" -F ' ' '{print $col}' "$file"
}

col() {
    awk '{print $1}'
}

gwt() {
    local REPO=$1
    local WORKING_BRANCH=$2

    # Remove the existing symbolic link
    rm "/opt/$REPO"

    # Create new symbolic links for the specified working branch
    ln -sfn "/opt/$REPO-repo/secret" "/opt/$REPO-repo/$WORKING_BRANCH"
    ln -sfn "/opt/$REPO-repo/.venv" "/opt/$REPO-repo/$WORKING_BRANCH"
    ln -sfn "/opt/$REPO-repo/.envrc" "/opt/$REPO-repo/$WORKING_BRANCH"
    ln -sfn "/opt/$REPO-repo/$WORKING_BRANCH" "/opt/$REPO"

    # Change directory and allow direnv
    cd "/opt/$REPO/" && direnv allow

    if [[ $REPO = "chomp" ]]; then
        touch /opt/chomp/etc/excludes.txt
    fi
}

ai_git_commit() {
    staged_files=$(git diff --name-only --cached)
    if [ -z "$staged_files" ]; then
        echo "No files are staged for commit."
    fi

    for file in $staged_files; do
        diff_output=$(git diff --cached "$file")

        # Use shell-gpt to generate a commit message for this file
        commit_message=$(echo "$diff_output" | sgpt "Generate a concise git commit message that summarizes the key changes in $file. Stay high-level and combine smaller changes to overarching topics. Skip describing any reformatting changes.")

        git commit -m "$commit_message" "$file"
    done
}

format_mac() {
    if [ -f "$1" ]; then
        rex='s/(..)/\1:/g' # add colon after every 2 chars
        # If the input is a file, read and format each MAC address in the file
        while read -r mac; do
            echo "$mac" | sed -E "$rex" | sed 's/:$//' | tr 'a-f' 'A-F' # second `sed` removes any extra colons
        done <"$1"
    else
        # If the input is a single MAC address, format it directly
        echo "$1" | sed -E "$rex" | sed 's/:$//' | tr 'a-f' 'A-F'
    fi
}

sgpt() {
    local query="$*"
    "$HOME/.dotfiles/.venv/bin/python3" -m sgpt "$query"
}
